version: "3.9"
services:
  data_generation:
    build: 
      context: ./src/data_generation
      dockerfile: Dockerfile
    image: data_generation_image:latest
    container_name: data_generation_container
    volumes:
      - ./File_Data_Volume:/File_Data_Volume

  model_training:
    build: 
      context: ./src/training
      dockerfile: Dockerfile
    image: model_training_image:latest
    container_name: model_training_container
    volumes:
      - ./File_Data_Volume:/File_Data_Volume
    depends_on:
      - data_generation

  api:
    build:
      context: ./src/app
      dockerfile: Dockerfile
    image: api_image:latest
    container_name: api_container
    volumes:
      - "./File_Data_Volume:/File_Data_Volume"
    ports:
      - "8000:8000"
    depends_on:
      - model_training


    
    



  
  

