version: "3.9"
services:
  data_collection:
    image: data_collection_image:latest
    container_name: data_collection_container
    volumes:
      - ./File_Data_Volume:/File_Data_Volume

  model_training:
    image: model_training_image:latest
    container_name: model_training_container
    volumes:
      - ./File_Data_Volume:/File_Data_Volume
    depends_on:
      - data_collection

  api:
    image: api_image:latest
    container_name: api_container
    volumes:
      - "./File_Data_Volume:/File_Data_Volume"
    ports:
      - "8000:8000"
    depends_on:
      - model_training


    
    



  
  

