# @format

name: Paris sportifs
on:
    push:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 
            - name: Test python Code 
              run: |
                  pip3 install -r requirements.txt 
                  cd codes/api/
                  pytest

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOSTNAME  }}
                  username: ubuntu
                  key: ${{ secrets.AWS_PRIVATE_KEY  }}
                  port: 22

                  script: |
                      mkdir -p /home/ubuntu/test_ssh_paris_sportifs/my_mlops_tennis_bet
                      cd /home/ubuntu/test_ssh_paris_sportifs/my_mlops_tennis_bet
                      sudo docker-compose down
                      git pull
                      sleep 5
                      docker-compose up -d --build

